name: Marcar presença Moodle

on:
  workflow_dispatch:  # roda manualmente
  schedule:
    - cron: '0 12 * * *' # opcional: todo dia às 12h UTC

jobs:
  marcar-presenca:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install selenium requests webdriver-manager

      - name: Rodar script Moodle
        run: python monitor_moodle.py
